// Code generated by "stringer -type=Biome"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Plain-0]
	_ = x[Weeds-1]
}

const _Biome_name = "PlainWeeds"

var _Biome_index = [...]uint8{0, 5, 10}

func (i Biome) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Biome_index)-1 {
		return "Biome(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Biome_name[_Biome_index[idx]:_Biome_index[idx+1]]
}
